# Generated by Django 2.2.2 on 2019-07-02 13:01

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(default=1, max_length=100, primary_key=True, serialize=False, verbose_name=django.db.models.fields.AutoField)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='logindata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='photodata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('class_stud', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('fees', models.CharField(default='50000', max_length=100)),
                ('fees_left', models.CharField(default='50000', max_length=100)),
                ('employee_email', models.CharField(max_length=100)),
            ],
        ),
    ]
