# Generated by Django 2.2.2 on 2019-07-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190702_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
