# Generated by Django 2.2.2 on 2019-07-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190706_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees_dep',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
