# Generated by Django 2.2.2 on 2019-07-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190706_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('tid', models.IntegerField(default=0)),
                ('amount', models.CharField(max_length=100)),
                ('depositedby', models.CharField(max_length=100)),
            ],
        ),
    ]
