# Generated by Django 2.2.2 on 2019-07-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_installment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='id',
        ),
        migrations.AlterField(
            model_name='installment',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
